package com.core.exception

import com.core.ReportExceptionAbstract
import com.core.ResponseCode

class ReportCanNotVacationCanceledAndApprovalAndRejectException : ReportExceptionAbstract(ResponseCode.CAN_NOT_VACATION_CANCELED_AND_APPROVAL_AND_REJECT)