version: '3'
services:
  mysql-master:
    image: biarms/mysql:5.7
    volumes:
      - ./sql/mysql_db/master:/mysql
      - ./sql/commerce/review:/review
      - ./sql/commerce/product:/product
      - ./sql/commerce/user:/user
      - ./sql/commerce/escrow:/escrow
      - ./seeding_m1.sh:/docker-entrypoint-initdb.d/seeding.sh
      - ./db/conf/master:/etc/mysql/conf.d
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user
      - MYSQL_USER=app_commerce
      - MYSQL_PASSWORD=test1234
    ports:
      - "53060:3306"
    networks:
      - docker-net

  mysql-slave:
    image: biarms/mysql:5.7
    volumes:
      - ./sql/mysql_db/slave:/mysql
      - ./sql/commerce/review:/review
      - ./sql/commerce/product:/product
      - ./sql/commerce/user:/user
      - ./sql/commerce/escrow:/escrow
      - ./seeding_m1.sh:/docker-entrypoint-initdb.d/seeding.sh
      - ./db/conf/slave:/etc/mysql/conf.d
    depends_on:
      - mysql-master
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user
      - MYSQL_USER=app_commerce
      - MYSQL_PASSWORD=test1234
    ports:
      - "53070:3306"
    networks:
      - docker-net

  redis-cluster:
    image: redis:5.0.8
    volumes:
      - ./redis:/redis
    environment:
      - START_PORT=30001
      - END_PORT=30003
      - TIMEOUT=1000
      - REPLICAS=0
      - PASSWORD=1234
    ports:
      - "30001-30003:30001-30003"
    entrypoint: /redis/docker-entrypoint.sh
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge