spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/masterdb
      username: app_commerce
      password: test1234
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/slavedb
      username: app_commerce
      password: test1234